Start Svalboard-specific firmware features documentation
svalboard/vial-qmk pull request #56
Opened 2024-06-22 22:23 UTC by vnegnev

Added a Markdown page in a `docs` folder, with a few screenshots. Most sections are currently empty, this is just establishing a place to add feature documentation later.

As new Svalboard-specific firmware features are added, it will be helpful to future users if the firmware developers add some feature documentation to this page (or new pages could be created and linked to).

In principle the contents of the `docs` folder could later be shifted to a GitHub wiki or similar, however this is far in the future and doesn't offer any advantages yet.

2024-06-23 15:14 UTC, ilc requested changes
Comments in-line,

2024-06-23 15:14 UTC, ilc commented on keyboards/svalboard/docs/automouse_allowed_keys.png
Please in-line this as code, so it is easier to update.

2024-06-23 15:14 UTC, ilc commented on keyboards/svalboard/readme.md
> +Hardware Supported: RP2040, Svalboard Alpha
Add, Svalboard Lightly.

2024-06-23 21:58 UTC, vnegnev commented on keyboards/svalboard/docs/automouse_allowed_keys.png
Done

2024-06-23 21:58 UTC, vnegnev commented on keyboards/svalboard/readme.md
> +Hardware Supported: RP2040, Svalboard Alpha
Done

2024-06-23 21:59 UTC, vnegnev commented
I've made the requested changes and rebased off the latest `vial` commit.

2024-06-23 22:40 UTC, ilc commented
LGTM.

2024-06-23 22:42 UTC, morganvenable commented
Lgtm

2024-06-23 22:44 UTC, morganvenable approved these changes
Approve

2024-06-24 18:42 UTC, ilc approved these changes
LGTM.

2024-06-24 18:43 UTC, merged